# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:2022.07.1
      resource_class: medium
    steps:
    - checkout
    - run:
        name: Fetch
        command: |
          python3 build/fbcode_builder/getdeps.py fetch --no-tests boost
          python3 build/fbcode_builder/getdeps.py fetch --no-tests ninja
          python3 build/fbcode_builder/getdeps.py fetch --no-tests cmake
          python3 build/fbcode_builder/getdeps.py fetch --no-tests double-conversion
          python3 build/fbcode_builder/getdeps.py fetch --no-tests fmt
          python3 build/fbcode_builder/getdeps.py fetch --no-tests gflags
          python3 build/fbcode_builder/getdeps.py fetch --no-tests glog
          python3 build/fbcode_builder/getdeps.py fetch --no-tests googletest
          python3 build/fbcode_builder/getdeps.py fetch --no-tests libevent
          python3 build/fbcode_builder/getdeps.py fetch --no-tests lz4
          python3 build/fbcode_builder/getdeps.py fetch --no-tests snappy
          python3 build/fbcode_builder/getdeps.py fetch --no-tests zstd
          python3 build/fbcode_builder/getdeps.py fetch --no-tests autoconf
          python3 build/fbcode_builder/getdeps.py fetch --no-tests automake
          python3 build/fbcode_builder/getdeps.py fetch --no-tests libtool
          python3 build/fbcode_builder/getdeps.py fetch --no-tests libsodium
          python3 build/fbcode_builder/getdeps.py fetch --no-tests xz
    - run:
        name: Build
        command: |
          python3 build/fbcode_builder/getdeps.py build --no-tests boost
          python3 build/fbcode_builder/getdeps.py build --no-tests ninja
          python3 build/fbcode_builder/getdeps.py build --no-tests cmake
          python3 build/fbcode_builder/getdeps.py build --no-tests double-conversion
          python3 build/fbcode_builder/getdeps.py build --no-tests fmt
          python3 build/fbcode_builder/getdeps.py build --no-tests gflags
          python3 build/fbcode_builder/getdeps.py build --no-tests glog
          python3 build/fbcode_builder/getdeps.py build --no-tests googletest
          python3 build/fbcode_builder/getdeps.py build --no-tests libevent
          python3 build/fbcode_builder/getdeps.py build --no-tests lz4
          python3 build/fbcode_builder/getdeps.py build --no-tests snappy
          python3 build/fbcode_builder/getdeps.py build --no-tests zstd
          python3 build/fbcode_builder/getdeps.py build --no-tests autoconf
          python3 build/fbcode_builder/getdeps.py build --no-tests automake
          python3 build/fbcode_builder/getdeps.py build --no-tests libtool
          python3 build/fbcode_builder/getdeps.py build --no-tests libsodium
          python3 build/fbcode_builder/getdeps.py build --no-tests xz
          python3 build/fbcode_builder/getdeps.py build --src-dir=. folly  --project-install-prefix folly:/usr/local
    - run:
        name: Copy artifacts
        command: python3 build/fbcode_builder/getdeps.py fixup-dyn-deps --strip --src-dir=. folly _artifacts/linux  --project-install-prefix folly:/usr/local --final-install-prefix /usr/local
    - store_artifacts:
        path: _artifacts
        destination: _artifacts
    - run: 
        name: Test folly
        command: python3 build/fbcode_builder/getdeps.py test --src-dir=. folly  --project-install-prefix folly:/usr/local
workflows:
  linux:
    jobs:
      - build
